version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/sh docker_dev_start.sh
    ports:
      - "4003:4000"
    depends_on:
      - reports
    links:
      - reports
  reports:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5435:5432"