{application,broadway_rabbitmq,
             [{applications,[kernel,stdlib,elixir,logger,broadway,amqp,
                             nimble_options,telemetry]},
              {description,"A RabbitMQ connector for Broadway"},
              {modules,['Elixir.BroadwayRabbitMQ.AmqpClient',
                        'Elixir.BroadwayRabbitMQ.Backoff',
                        'Elixir.BroadwayRabbitMQ.Producer',
                        'Elixir.BroadwayRabbitMQ.RabbitmqClient']},
              {registered,[]},
              {vsn,"0.7.1"}]}.
